blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    #path('', views.post_list, name = 'post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name = 'post_detail'),
]

hawa_site/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('account/', include('accounts.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    #path('tinymce/', include('tinymce.urls')),
]

templates/base.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<div class="container">
    <h1>
        Welcome to my Django Site
    </h1>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #008080;color: white;">
  <a class="navbar-brand" href="{% url 'home' %}">Konoha</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
      </li>
    </ul>
      <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <a class="nav-link" href="#">{{user.first_name}}</a>
          <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}" style="font-weight:bold;">Logout</a>
      </li>
          {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'signup' %}">SignUp</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% block content %}
{% endblock %}
    <br><br>
<div style="
   left: 0;
   bottom: 0;
   height:50px;
   width: 100%;
   background-color: teal;
   color: white;
   text-align: center;">
    <h3>&copy;Pysantosh</h3>
</div>
</div>

templates/home.html
{% extends 'base.html' %}

templates/pagination.html
<div class="pagination">
<span class="step-links">
{% if page.has_previous %}
<a href="?page={{ page.previous_page_number }}">Previous</a>
{% endif %}
<span class="current">
Page {{ page.number }} of {{ page.paginator.num_pages }}.
</span>
{% if page.has_next %}
<a href="?page={{ page.next_page_number }}">Next</a>
{% endif %}
</span>
</div>